/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_imooc_extractinfotest_MainActivity */

#ifndef _Included_com_imooc_extractinfotest_MainActivity
#define _Included_com_imooc_extractinfotest_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_imooc_extractinfotest_MainActivity
 * Method:    mp4ToAac
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_imooc_extractinfotest_MainActivity_mp4ToAac
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
